### ISSUE TITLE
maximum recursion error when trying to run tfchain client tests

### ISSUE THREAD

**Issue by zaibon** [threefoldtecharchive/jumpscaleX_archived#279]
I tried to run the tests for the tfchain client using : 
```
js_shell 'j.clients.tfchain.test(name="reservation")'
```
And end up with a maximum recursion error:
```
3BOTDEVEL:jsx:tests: js_shell 'j.clients.tfchain.test(name="reservation")'
* ##: TEST RUN: RESERVATION
* ##: TEST RUN: 200_RESERVATION.PY
* BCDB INIT DONE:system


EXCEPTION

        /sandbox/bin/js_shell                                        : 25  : exec(toexec)
        <string>                                                     : 1   : 
        Jumpscale/clients/blockchain/tfchain/TFChainClientFactory.py : 43  : self._test_run(name=name)
        /sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py  : 444 : res = self.__test_run(name=name, obj_key=obj_key, die=die, **kwargs)
        /sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py  : 482 : self.__test_run(name=bname, obj_key=obj_key, **kwargs)
        /sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py  : 499 : res = method(self=self, **kwargs)
        umpscale/clients/blockchain/tfchain/tests/200_reservation.py : 24  : c = j.clients.tfchain.new("mydevclient", network_type="DEV")
        ox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBaseConfigs.py : 59  : self._children[name] = kl(parent=self, data=data, **kwargs)
        b/jumpscale/Jumpscale/core/BASECLASSES/JSBaseConfigParent.py : 17  : JSFactoryBase.__init__(self, topclass=False)
        ox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSFactoryBase.py : 13  : obj = kl(parent=self)
        ox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBaseConfigs.py : 9   : JSBase.__init__(self, parent=parent, topclass=False)
        /sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py  : 16  : self._class_init()  # is needed to init class properties
        ox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBaseConfigs.py : 27  : JSBase._class_init(self)
        /sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py  : 47  : if hasattr(parent,"__jslocation__"):
        ox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBaseDataObj.py : 128 : if attr in self._schema.propertynames:
        ox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBaseDataObj.py : 41  : if self._schema_ is None:
        ox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBaseDataObj.py : 128 : if attr in self._schema.propertynames:
        ox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBaseDataObj.py : 41  : if self._schema_ is None:
        ox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBaseDataObj.py : 128 : if attr in self._schema.propertynames:
        ox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBaseDataObj.py : 41  : if self._schema_ is None:
        ox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBaseDataObj.py : 128 : if attr in self._schema.propertynames:
...
...
...
Wed27 10:44 <string>         -   1 - <module>                           : EXCEPTION: maximum recursion depth exceeded while calling a Python object
CANNOT CONTINUE
```

**Comment by zaibon** [comment]
Having the same bug when trying to use schema now.
```python
JSX> schema = j.data.schema.get(j.sal.fs.readFile('/sandbox/code/github/threefoldtech/jumpscaleX/Jumpscale/clients/blockchain/tfchain/schemas/reservation_namespace.schema'))                                                                  
JSX> o = schema.new()                                                                                                                                                                                                                          
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/data/schema/Schema.py", line 282, in new
    r = self.get(data=data,model=model)
  File "/sandbox/lib/jumpscale/Jumpscale/data/schema/Schema.py", line 273, in get
    obj = self.objclass(schema=self, data=data, capnpbin=capnpbin, model=model)
  File "/sandbox/lib/jumpscale/Jumpscale/data/schema/Schema.py", line 258, in objclass
    name="schema_%s" % self.key, obj_key="ModelOBJ", path=tpath, obj=self, objForHash=self._md5)
  File "/sandbox/lib/jumpscale/Jumpscale/tools/jinja2/Jinja2.py", line 141, in code_python_render
    out = t.render(j=j, DIRS=j.dirs, BASENAME=BASENAME, **args)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 14, in top-level template code
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
  File "/sandbox/lib/jumpscale/Jumpscale/data/schema/SchemaProperty.py", line 36, in default_as_python_code
    return self.jumpscaletype.python_code_get(self.default)
  File "/sandbox/lib/jumpscale/Jumpscale/data/schema/SchemaProperty.py", line 32, in default
    return self.jumpscaletype.default_get()
  File "/sandbox/lib/jumpscale/Jumpscale/data/types/TypeBaseClasses.py", line 197, in default_get
    return self.clean(self._default)
  File "/sandbox/lib/jumpscale/Jumpscale/data/types/AdvTypes.py", line 79, in clean
    return self.default_get()
  File "/sandbox/lib/jumpscale/Jumpscale/data/types/TypeBaseClasses.py", line 197, in default_get
    return self.clean(self._default)
  File "/sandbox/lib/jumpscale/Jumpscale/data/types/AdvTypes.py", line 79, in clean
    return self.default_get()
  File "/sandbox/lib/jumpscale/Jumpscale/data/types/TypeBaseClasses.py", line 197, in default_get
    return self.clean(self._default)
  File "/sandbox/lib/jumpscale/Jumpscale/data/types/AdvTypes.py", line 79, in clean
    return self.default_get()
  File "/sandbox/lib/jumpscale/Jumpscale/data/types/TypeBaseClasses.py", line 197, in default_get
    return self.clean(self._default)
  File "/sandbox/lib/jumpscale/Jumpscale/data/types/AdvTypes.py", line 79, in clean
    return self.default_get()
  File "/sandbox/lib/jumpscale/Jumpscale/data/types/TypeBaseClasses.py", line 197, in default_get
    return self.clean(self._default)
  File "/sandbox/lib/jumpscale/Jumpscale/data/types/AdvTypes.py", line 79, in clean
    return self.default_get()
  File "/sandbox/lib/jumpscale/Jumpscale/data/types/TypeBaseClasses.py", line 197, in default_get
    return self.clean(self._default)
  File "/sandbox/lib/jumpscale/Jumpscale/data/types/AdvTypes.py", line 79, in clean
    return self.default_get()
  File "/sandbox/lib/jumpscale/Jumpscale/data/types/TypeBaseClasses.py", line 197, in default_get
    return self.clean(self._default)
  File "/sandbox/lib/jumpscale/Jumpscale/data/types/AdvTypes.py", line 79, in clean
    return self.default_get()
  File "/sandbox/lib/jumpscale/Jumpscale/data/types/TypeBaseClasses.py", line 197, in default_get
    return self.clean(self._default)
.....
  File "/sandbox/lib/jumpscale/Jumpscale/data/types/TypeBaseClasses.py", line 197, in default_get
    return self.clean(self._default)
  File "/sandbox/lib/jumpscale/Jumpscale/data/types/AdvTypes.py", line 79, in clean
    return self.default_get()
  File "/sandbox/lib/jumpscale/Jumpscale/data/types/TypeBaseClasses.py", line 197, in default_get
    return self.clean(self._default)
  File "/sandbox/lib/jumpscale/Jumpscale/data/types/AdvTypes.py", line 79, in clean
    return self.default_get()
  File "/sandbox/lib/jumpscale/Jumpscale/data/types/TypeBaseClasses.py", line 197, in default_get
    return self.clean(self._default)
RecursionError: maximum recursion depth exceeded
```

**Comment by despiegk** [comment]
resolved

**Comment by zaibon** [comment]
https://github.com/threefoldtech/jumpscaleX/commit/a977e51a066a6643779e48f8b9039bd5ea894346
(don't hesitate to link the commit that solve an issue when closing it)

**Comment by zaibon** [comment]
I just pulled lastest development branch of jsx (b29e2b9858ba7e257cd5787c890f1d32021ba70d)
And the recursion error is back:
```python
3BOTDEVEL:jsx:~: kosmos 


EXCEPTION

        /sandbox/bin/kosmos                                          : 149 : if n.load(die=False) is False:
        /sandbox/lib/jumpscale/Jumpscale/data/nacl/NACL.py           : 205 : if j.clients.sshagent.available_1key_check():
        sandbox/lib/jumpscale/Jumpscale/clients/sshagent/SSHAgent.py : 421 : if not self.available():
        sandbox/lib/jumpscale/Jumpscale/clients/sshagent/SSHAgent.py : 102 : self.check()
        sandbox/lib/jumpscale/Jumpscale/clients/sshagent/SSHAgent.py : 82  : if j.core.myenv.config["SSH_KEY_DEFAULT"] == "" and len(self.key_names)==1:
        sandbox/lib/jumpscale/Jumpscale/clients/sshagent/SSHAgent.py : 126 : self.check()
        sandbox/lib/jumpscale/Jumpscale/clients/sshagent/SSHAgent.py : 82  : if j.core.myenv.config["SSH_KEY_DEFAULT"] == "" and len(self.key_names)==1:
        sandbox/lib/jumpscale/Jumpscale/clients/sshagent/SSHAgent.py : 126 : self.check()
        sandbox/lib/jumpscale/Jumpscale/clients/sshagent/SSHAgent.py : 82  : if j.core.myenv.config["SSH_KEY_DEFAULT"] == "" and len(self.key_names)==1:
        sandbox/lib/jumpscale/Jumpscale/clients/sshagent/SSHAgent.py : 126 : self.check()
        sandbox/lib/jumpscale/Jumpscale/clients/sshagent/SSHAgent.py : 82  : if j.core.myenv.config["SSH_KEY_DEFAULT"] == "" and len(self.key_names)==1:
...
...
        sandbox/lib/jumpscale/Jumpscale/clients/sshagent/SSHAgent.py : 82  : if j.core.myenv.config["SSH_KEY_DEFAULT"] == "" and len(self.key_names)==1:
        sandbox/lib/jumpscale/Jumpscale/clients/sshagent/SSHAgent.py : 126 : self.check()
        sandbox/lib/jumpscale/Jumpscale/clients/sshagent/SSHAgent.py : 82  : if j.core.myenv.config["SSH_KEY_DEFAULT"] == "" and len(self.key_names)==1:
        sandbox/lib/jumpscale/Jumpscale/clients/sshagent/SSHAgent.py : 126 : self.check()
        sandbox/lib/jumpscale/Jumpscale/clients/sshagent/SSHAgent.py : 82  : if j.core.myenv.config["SSH_KEY_DEFAULT"] == "" and len(self.key_names)==1:
        sandbox/lib/jumpscale/Jumpscale/clients/sshagent/SSHAgent.py : 126 : self.check()
        sandbox/lib/jumpscale/Jumpscale/clients/sshagent/SSHAgent.py : 67  : if not j.sal.fs.exists(self.ssh_socket_path):
        sandbox/lib/jumpscale/Jumpscale/clients/sshagent/SSHAgent.py : 18  : if "SSH_AUTH_SOCK" in os.environ:
        /usr/lib/python3.6/_collections_abc.py                       : 666 : self[key]
        /usr/lib/python3.6/os.py                                     : 666 : value = self._data[self.encodekey(key)]

Thu04 08:15 NACL.py          - 183 - load                               : EXCEPTION: maximum recursion depth exceeded
CANNOT CONTINUE
```

**Comment by despiegk** [comment]
its not same bug, have nothing to do with each other, very simple to fix, just check the logic of what happens for sshagent and you'll see where bug is

**Comment by zaibon** [comment]
> its not same bug, have nothing to do with each other, 

Indeed, that's why I changed the title, but right, I should probably have open a new issue.
I'll move !

>  very simple to fix

nice !
