### ISSUE TITLE
did not receive email when reserving capacity

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtecharchive/jumpscaleX_archived#323]
JSX branch **development**

After reserving zdb I did not receive a confirmation email

following input was used:

```python
JSX> w.balance
wallet balance on height 249898 at 2019/04/09 14:30:07
1057.95 TFT available and 0 TFT locked

JSX> result = w.capacity.reserve_zdb_namespace(
   2     email='dylan@threefold.tech', # the email on which you will received the connection information
   3     threebot_id='mybot.dylan', # your threebot id, it can be any of the names you gave to your 3bot
   4     location='5480284e24b8', # name of the farm or node id where to deploy the workload
   5     size=5, # Size of the namespace in GB
   6     disk_type='ssd', # type of disk, It can be 'ssd' or 'hdd'
   7     mode='seq', # the 0-db mode. It can be 'seq' or 'user'. To know more about 0-DB mode: https://github.com/threefoldtech/0-db#running-modes
   8     password=None)
JSX> result.submitted
True

JSX> w.balance
wallet balance on height 249902 at 2019/04/09 14:38:42
641.35 TFT available and 0 TFT locked
```

**Comment by DylanVerstraete** [comment]
@zaibon This is fixed now, emails are always sent right ?

**Comment by zaibon** [comment]
Yep should be good now.

**Comment by 0xIslamTaha** [comment]
@zaibon I can see that occasionally still happening.

```python
wallet.balance                                                                                                                                                             
wallet balance on height 298624 at 2019/06/16 09:39:55
3499.7 TFT available and 0 TFT locked

JSX> wallet.capacity.reserve_zos_vm(email="tft.testing.19@gmail.com", threebot_id="my3bot001.example", location="freefarm", size=1)                                             
Sun 16 09:45:40 GedisClient.py   - 138 - j.clients.gedis:gedisclient        : redisclient: notary.grid.tf:5000 
Sun 16 09:45:41 GedisClient.py   - 102 - j.clients.gedis:gedisclient        : cmds for actor:notary_actor
TransactionSendResult(transaction=transaction v1 79b58a9e5debb631bca4cb8c0b63623804f6811013ac51107ebc009797f73888, submitted=True)

JSX> wallet.balance                                                                                                                                                             
wallet balance on height 298625 at 2019/06/16 09:46:08
3457.95 TFT available and 0 TFT locked
```

I'm using JSX development

**Comment by zaibon** [comment]
One of the testnet explorer was out of sync, so the new reservation were not picked up by the grid broker.
Explorer is not catching up, grid broker will get the new transaction bit by bit now.

**Comment by serboctor** [comment]
@0xIslamTaha was still having issues after the sync so I took a look at the code that lists the transaction. I don't see anything fishy, and if the nodes are in sync, then I don't see a reason why the transaction wouldn't reach the grid broker.
However, while working on this task  https://github.com/threefoldtech/grid_broker/issues/13  and testing with a local grid broker I noticed the following:

The installation of a reservation usually takes a couple of minutes, but there were a couple of instances where the installation took a very long time and wouldn't finish and sometimes it is blocked while getting the connection info which makes me feel like this might be a zerotier issue. 
The grid broker template can't process more than one transaction at a time, and as a result, if an installation of a reservation takes too long or blocks for whatever reason, the rest of the transactions won't be processed until it is done.

@0xIslamTaha I added a lot of log statements in the template so we can track when a transaction has been processed and if any errors occur. The grid broker will be updated next week with the new code, if this happens again with you, let me know and I'll check the logs and try to figure out what went wrong. Just make sure you have the transaction id saved so I can know what to look for.

**Comment by serboctor** [comment]
I faced this issue again while testing with a local grid_broker, I did an extension and I could see the the broker checking for new transaction but somehow not seeing the new transaction. 
Luckily I was able to reproduce it, it doesn't always happen. 
The broker depends on the transactions list being sorted by time, and it keeps a track of the number of the transactions processed and uses this counter to slice the transactions list. https://github.com/threefoldtech/grid_broker/blob/master/templates/grid_broker/grid_broker.py#L292
In this picture you can see a reservation that I did, and after I got the confirmation email, I did an extension for the reservation.
![Screenshot from 2019-07-11 19-02-43](https://user-images.githubusercontent.com/6323012/61071139-9eabc500-a410-11e9-8937-973b4b22eec2.png)

This shows a list of the transactions that are expected to be sorted by time, however, you can see at the end of the list, the transaction for the reservation comes at the end of the list after the extension not before it, even though the extension was the last transaction I did on this broker. Hence, when the watcher did the slicing, it got the reservation transaction again, then disregarded it because it already processed it before. 

![Screenshot from 2019-07-11 19-02-49](https://user-images.githubusercontent.com/6323012/61071254-e599ba80-a410-11e9-8fe6-fefd543f44a8.png)

**Comment by serboctor** [comment]
After digging deeper, it seems that transactions are sorted by `block_height` and since we can have several transactions within the same block, we can't guarantee they'd be ordered chronologically. As a compromise between rechecking all transactions and between the current implementation, I've added a buffer which is the number of transactions we would recheck. This number should be roughly equal to the maximum number of transactions than can exist in a block. It will be used as a safety measure to make sure no transactions are dropped. 
I already did the change locally, and I am waiting on @LeeSmet to confirm the correct estimated number to push it.

**Comment by serboctor** [comment]
Fixed by https://github.com/threefoldtech/grid_broker/commit/5cfbecfaa14dbfa756e734752227ee4af62691a0

**Comment by serboctor** [comment]
After some discussions with @LeeSmet I learned that my buffer fix won't necessarily ensure that no transactions are dropped. Unconfirmed transactions have block_height 0 and once they become confirmed, it is possible that they join a block lower than the latest one. Those 2 facts make it impossible to depend on slicing the transaction list. For now I refactored the watcher to go over all transactions, which is an overhead but until the tfchain offer a better way to stream transactions, that's the way it'll have to be.  
https://github.com/threefoldtech/grid_broker/commit/0a73bb5201ddc28d32999c9c415c1da4db5cf418

**Comment by siddiquagig** [comment]
Verified its working now:

```

JSX> result = w.capacity.reserve_zos_vm(email='ahmed.s@incubaid.com',threebot_id='ahmed3bot531.reserve',location='ac1f6b272370',size=1,duration=1)
Mon 29 08:52:43 BCDBMeta.py      - 166 - bcdbmeta:bcdbmeta                  : schema set in BCDB:system meta:jumpscale.threefold_directory.client (md5:'2c967c2522e32111bb0b98a35312f34a')
Mon 29 08:52:43 BCDBMeta.py      - 175 - bcdbmeta:bcdbmeta                  : new schema in meta:
system: jumpscale.threefold_directory.client:2c967c2522e32111bb0b98a35312f34a
Mon 29 08:52:43 BCDBMeta.py      - 133 - bcdbmeta:bcdbmeta                  : save meta:system
Mon 29 08:52:43 BCDB.py          - 409 - bcdb:bcdb                          : load model:jumpscale.threefold_directory.client
Mon 29 08:52:43 BCDBMeta.py      - 163 - bcdbmeta:bcdbmeta                  : schema set in BCDB:system meta:jumpscale.threefold_directory.client (EXISTING)
Mon 29 08:53:36 BCDBMeta.py      - 166 - bcdbmeta:bcdbmeta                  : schema set in BCDB:system meta:jumpscale.gedis.client (md5:'4c47b74e2101b80082d468c0ce37b507')
Mon 29 08:53:36 BCDBMeta.py      - 175 - bcdbmeta:bcdbmeta                  : new schema in meta:
system: jumpscale.gedis.client:4c47b74e2101b80082d468c0ce37b507
Mon 29 08:53:36 BCDBMeta.py      - 133 - bcdbmeta:bcdbmeta                  : save meta:system
Mon 29 08:53:37 BCDB.py          - 409 - bcdb:bcdb                          : load model:jumpscale.gedis.client
Mon 29 08:53:37 BCDBMeta.py      - 163 - bcdbmeta:bcdbmeta                  : schema set in BCDB:system meta:jumpscale.gedis.client (EXISTING)
Mon 29 08:53:37 GedisClient.py   - 138 - j.clients.gedis:gedisclient        : redisclient: notary.grid.tf:5000
Mon 29 08:53:39 GedisClient.py   - 102 - j.clients.gedis:gedisclient        : cmds for actor:notary_actor


JSX> result.transaction
transaction v1 557525ec11e260b095d78cde9b98792eed90b99c00cd6b38fde82d5fe4fcd843


```


Also got the success email:

![ready](https://user-images.githubusercontent.com/25789724/62036104-2f044b00-b202-11e9-819d-82fa8e82392c.JPG)




```

3BOTDEVEL:3bot:jumpscaleX: git log -1
commit 4ad8a95db184651fb5231a854add2b61cf39d7bf (HEAD -> development, origin/development)
Merge: 0eaf5449 e09a4a2f
Author: Reem Khamis <rkhamis@users.noreply.github.com>
Date:   Wed Jul 10 16:25:56 2019 +0200

    Merge pull request #691 from threefoldtech/reservation_security

    Reservation security
```
